# -*- coding: utf-8 -*-
"""Capstone Data Engineering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yTmu3t1T_sbCuQoxfNCqmfS_qPu8nl5X
"""

import sqlite3
import pandas as pd
prefix='https://raw.githubusercontent.com/SanthoshSLV/Dataset/main/'
url={'geolocation_dataset':['Olist_geographic_data_1.csv','Olist_geographic_data_2.csv'],
'customers_dataset':['olist_customers_dataset.csv'],
'order_items_dataset':['olist_order_items_dataset.csv'],
'order_payments_dataset':['olist_order_payments_dataset.csv'],
'order_reviews_dataset':['olist_order_reviews_dataset.csv'],
'orders_dataset':['olist_orders_dataset.csv'],
'products_dataset':['olist_products_dataset.csv'],
'sellers_dataset':['olist_sellers_dataset.csv'],
'category_name_translation':['product_category_name_translation.csv']}

connection=sqlite3.connect('DSAILVA_Capstone_DB')
cursor=connection.cursor()

data={}
for key,value in url.items():
  temp=pd.read_csv(prefix+url[key][0])
  if len(url[key])>1:
    for index in range(1,len(url[key])):
      temp=pd.concat([temp,pd.read_csv(prefix+url[key][index])],ignore_index=True)
    data[key]=temp
  else:
    data[key]=temp

for name,dataframe in data.items():
  dataframe.to_sql(name, connection, if_exists='replace', index = False)

cursor.execute('''SELECT name FROM sqlite_master WHERE type='table';''')
result=cursor.fetchall()

for row in result:
    print(row)

for name in result:
  print(name[0],'\nColumn names')
  cursor.execute(f'''select name from PRAGMA_TABLE_INFO('{name[0]}');''')
  for row in cursor.fetchall():
    print(row,end=" ")
  print('\nNumber of Rows:',end="")
  cursor.execute(f'select count(*) from {name[0]}')
  for row in cursor.fetchall():
    print(row[0])
  print("\n")